# Generated by Django 3.2.8 on 2025-08-26 13:56

import backend.core
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('honeypot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', backend.core.PrefixedUUIDField(editable=False, max_length=48, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('code_name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Target',
                'db_table': 'control_server_targets',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', backend.core.PrefixedUUIDField(editable=False, max_length=48, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to=settings.AUTH_USER_MODEL)),
                ('honeypage', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='honeypot.honeypage')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='control_server.target')),
            ],
            options={
                'verbose_name': 'Experiments',
                'db_table': 'control_server_experiments',
                'ordering': ['-pk'],
            },
        ),
    ]
