services:
    tlsfp:
        build:
            context: ./tlsfp-rp
            dockerfile: Dockerfile
        volumes:
            - /etc/letsencrypt/live/${DOMAIN_NAME:?error}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN_NAME:?error}/fullchain.pem
            - /etc/letsencrypt/live/${DOMAIN_NAME:?error}/privkey.pem:/etc/letsencrypt/live/${DOMAIN_NAME:?error}/privkey.pem
        env_file:
            - .env/${ENV_FILE:?error}
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - nginx
            - backend

    db:
        restart: unless-stopped
        container_name: db
        image: postgres:12.0-alpine
        volumes:
            - postgres_data_volume:/var/lib/postgresql/data/
        env_file:
            - .env/${ENV_FILE:?error}

    pgbackups:
        container_name: db-backup
        image: prodrigestivill/postgres-backup-local
        restart: unless-stopped
        volumes:
            - ./db_backups:/backups
        links:
            - db
        depends_on:
            - db
        env_file:
            - .env/${ENV_FILE:?error}
        environment:
            - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
            - SCHEDULE=@every 0h30m00s
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=8080

    backend:
        restart: unless-stopped
        env_file:
            - .env/${ENV_FILE:?error}
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        volumes:
            - backend_static_volume:/usr/src/backend/run/static

        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --timeout 90 --workers=3
        depends_on:
            - db

    nginx:
        image: nginx:latest
        restart: unless-stopped
        env_file:
            - .env/${ENV_FILE:?error}
        volumes:
            - ./nginx/${NGINX_FILE:?error}:/etc/nginx/conf.d/default.conf
            - ./nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
            - /etc/letsencrypt/live/${DOMAIN_NAME:?1}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN_NAME:?2}/fullchain.pem
            - /etc/letsencrypt/live/${DOMAIN_NAME:?3}/privkey.pem:/etc/letsencrypt/live/${DOMAIN_NAME:?4}/privkey.pem
            - nginx_logs_volume:/var/log/nginx
            - backend_static_volume:/var/www/backend/static
        depends_on:
            - backend

volumes:
    backend_static_volume:
    postgres_data_volume:
    nginx_logs_volume:
