# Generated by Django 3.2.8 on 2025-08-26 13:56

import backend.core
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Honeypage',
            fields=[
                ('id', backend.core.PrefixedUUIDField(editable=False, max_length=48, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(default='http', max_length=5)),
                ('subdomain', models.CharField(default='', max_length=128)),
                ('path', models.CharField(blank=True, default='', max_length=128)),
                ('book_id', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='children', to='honeypot.honeypage')),
            ],
            options={
                'verbose_name': 'Honeypage',
                'db_table': 'honeypot_honeypages',
                'ordering': ['-created_at'],
                'default_permissions': ['view'],
                'unique_together': {('source', 'book_id', 'color')},
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', backend.core.PrefixedUUIDField(editable=False, max_length=48, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('absolute_url', models.TextField(blank=True)),
                ('http_host', models.CharField(blank=True, max_length=512)),
                ('subdomain', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('ja3_data', models.TextField(blank=True, null=True)),
                ('ja3_fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('ja4_data', models.TextField(blank=True, null=True)),
                ('ja4_fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('scheme', models.CharField(blank=True, max_length=24, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('location_data', models.TextField(blank=True, null=True, verbose_name='GeoIP 2 Location')),
                ('response', models.TextField(blank=True, verbose_name='Response')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'db_table': 'honeypot_access_logs',
                'ordering': ['-timestamp'],
                'default_permissions': ['view'],
            },
        ),
    ]
